### ISSUE TITLE
Decompose components before interpolation to avoid rounding differences

### ISSUE THREAD

**Issue by punchcutter** [googlei18n/ufo2ft#192]
As @schriftgestalt writes at https://github.com/googlei18n/noto-fonts/issues/1012

> The solution is to not round any coordinates (the nodes and the position of the components) until the components are decomposed.

**Comment by anthrotype** [comment]
@moyogo added a `--no-round` option to fontmake (and glyphsLib) that makes it so that when mutatorMath interpolates instances it keeps float values and does not round to integers.

https://github.com/googlei18n/fontmake/pull/358

I wonder if that could help with the above mentioned issue?

(note that this is only available on master branch -- I still haven't tagged a new fontmake release, as there's some unfinished stuff in the interaction between fontmake and ufo2ft. I plan to do it very soon)

**Comment by behdad** [comment]
I haven't been following these discussions, but is there a need for the `--no-round` option?  If that's the only useful option maybe that should be the default?  Or is that what goes into glyf table's composite glyph flags?

**Comment by anthrotype** [comment]
No, this doesn't have to do with the glyf table's composite glyph flags, but with the rounding of coordinates and any other numeric values in the interpolated UFO instances. 
I also believe we should make --no-round the default. I don't see much use in the current default behaviour of fontmake (mutatorMath). The values are going to be rounded anyway inside fonttools when exporting to TTF or OTF (for the latter, rounding can be controlled via ufo2ft's roundTolerance argument, but that's not exposed in fontmake's command line yet).

@moyogo are you ok if we make it the default and drop the option altogether?

**Comment by moyogo** [comment]
@anthrotype @behdad I’m fine with no-round as the default but having the option is good.
Suppose one has two masters but wants to generate a new intermediary master to further work on, it may be desirable to round straight from fontmake instead of having the font editor doing it when it may or may not.

**Comment by schriftgestalt** [comment]
There needs to be an option to control rounding on some point. Because some fonts might need rounding and some don't.

**Comment by anthrotype** [comment]
what kind of rounding are you referring to?
here we're discussing about the rounding that takes place at the source level, following the interpolation, rather than the one that occurs at export time, where different output formats may require integers or allow floats.

**Comment by anthrotype** [comment]
Also, I think the title of the current issue is a bit confusing.

"not round any coordinates until the components are decomposed" (as in the quote above) is a different thing from "decomposing components before interpolation to avoid rounding issues".

we want to do the first (avoid rounding the interpolated sources) instead of the second (decompose before the interpolation, unnecessarily assumed to always round results).

**Comment by punchcutter** [comment]
@anthrotype Sorry, the title isn't 100% clear. I'm not sure why it became that instead of "not round any coordinates until the components are decomposed".

**Comment by anthrotype** [comment]
this should be fixed with https://github.com/googlei18n/fontmake/pull/390
