### ISSUE TITLE
xAvgCharWidth is calculated differently by fontTools and FontVal

### ISSUE THREAD

**Issue by madig** [googlei18n/ufo2ft#195]
1. Build https://github.com/daltonmaag/ubuntu
2. Check Ubuntu-R.ttf with FontVal.

Result:

E2135 | The xAvgCharWidth field does not equal the calculated value | actual = 605, calc = 453
-- | -- | --

Not sure what to make of this.

**Comment by khaledhosny** [comment]
Most likely a bug in FontVal (using what was described in old versions of the spec).

**Comment by khaledhosny** [comment]
Compare [`OS/2` version 0](https://www.microsoft.com/typography/otspec/os2ver0.htm#acw) text with [current version](https://www.microsoft.com/typography/otspec/os2.htm#acw). It is a useless relic from a non-internationalized part, I suggest not to put much effort into it.

**Comment by madig** [comment]
I wouldn't care about it if FontVal didn't flag it as an error.

**Comment by khaledhosny** [comment]
Well, FontVal is known to flag things as errors for bogus reasons, this apparently didn’t change after it became open source. I personally just ignore its reports, I’m yet to find anything useful there. Lint tools are good as long as what they error about is actually relevant.

**Comment by HinTak** [comment]
@khaledhosny :that you don't know the reasons (of Microsoft folks' decisions) just means it is "unknown" / "not disclosed", rather than "bogus". Please feel free to catch some Microsoft folks and demands some explanations/answers, and good luck with it.

Granted, for once, you are correct - https://github.com/HinTak/Font-Validator/blob/master/OTFontFileVal/val_OS2.cs - line 105, does one way of calculation when OS/2 table is "exactly 3", and does something else if not. It should be changed to "larger than or equal to 3".

In the future, @madig you can look at the source itself - mostly the actual tests are in https://github.com/HinTak/Font-Validator/blob/master/OTFontFileVal/val_{table}.cs where you search for the actual test, like line 74 , with `v.PerformTest(T.OS_2_xAvgCharWidth)` .

I'll go and change the code now.

**Comment by khaledhosny** [comment]
The bogus remark was not only about this particular error, but things like:
```
E	| E2101	| There are undefined bits set in fsSelection field
		Bit(s) 7
```
(complaining about `USE_TYPO_METRICS`, in the spec since 2008).

or
```
E	| E5400	| The FeatureParams field is not null
		FeatureList, FeatureRecord[27](ss01), FeatureTable
```
(non-null is allowed in the spec since 2000)

or
```
E	| E5700	| The LookupFlag reserved bits are not all set to zero
		LookupList, Lookup[29]
```
(complaining about `useMarkFilteringSet` flag, in the spec since 2010)

Granted, that would have made since a decade ago or so, but a validator that did not keep up with the spec updates in the last decade (at least) is of no use to me personally and the errors it is making are bogus *now*.

**Comment by behdad** [comment]
> @khaledhosny :that you don't know the reasons (of Microsoft folks' decisions) just means it is "unknown" / "not disclosed", rather than "bogus".

You are assuming that the person writing that code back then, knew better than Khaled does today.  I know this industry, and I know that you are wrong. :)

**Comment by HinTak** [comment]
The bulk of Font Validator code was last updated around 2009 - according to hints in the initial zip file I received. So far I have been putting my time where it matters - filling in the parts that Microsoft did not release, and at the glyph level tests (hinting/rasterization, glyf/contours, and EDBC etc). The other tables are relatively easy to do/update, and doesn't really require a lot of know-how to do. Please feel free to update them.

@khaledhosny @behdad - I do not want to be drawn into that debate again. Font Validator captures many of Microsoft's wishes/preferences as well as specs. That's how it is. You may not agree with some of their preferences (such as undocumented use of some tables, and therefore make them a necessity), but I do not wish to discuss why they did what they did, or override their past decisions. If you wish to change Font Validator in a way that override their past decisions, please discuss and consult them. I am okay to accept an update to the documentation (https://github.com/HinTak/Font-Validator/blob/master/GenerateFValData/OurData.xml ) to provide more information about specific messages and their appropriateness under specific usage - e.g. I added to one or two of them that that warning/error does not matter if the font is intended only for lilbre platforms (i.e. freetype). But that's the extent I am happy to go forward.

This can be closed now.

**Comment by HinTak** [comment]
I have opened https://github.com/HinTak/Font-Validator/issues/34 to track the issues @khaledhosny raised, though these sort of things ( code from Microsoft I have not touched) I'd prefer them to be filed "upstream".

By tracking, I just mean "hope to spend some time looking at it in some details (and not forgotten about it)". It does not necessarily mean that changes will be made, or in any directions; nor within any time scale.

**Comment by davelab6** [comment]
> I'd prefer them to be filed "upstream".

Microsoft has abandoned the FontVal project. Nothing will happen upstream from anyone at Microsoft, ever.

**Comment by davelab6** [comment]
> This can be closed now.

@madig please close :)
