### ISSUE TITLE
Group names hard coded in KernFeatureWriter, fails with @MMK_L_*-style group names.

### ISSUE THREAD

**Issue by justvanrossum** [googlei18n/ufo2ft#22]
Compare with the ufo2fdk KernFeatureWriter.getReferencedGroups() method, which looks at the actual group names being referenced from the kerning data.
I see there's some code for @MMK_L_*-style names, but it's not called. But it's not a good idea to do it that way: there should be no need to make assumptions about the group names.

**Comment by jamesgk** [comment]
The ufo2ft KernFeatureWriter class attributes are designed to be overwritten by subclasses as necessary, depending on how your UFO groups or feature classes are named ([example](https://github.com/googlei18n/fontmake/blob/3457d972563a4bf38e55e5096f6cc974dd13791c/Lib/fontmake/font_project.py#L165)).

The writer naively writes class definitions and kerning rules based off of what's provided in the UFO. I did this because the UFO spec seems to largely decouple groups and kerning contents -- in the [kerning section](http://unifiedfontobject.org/versions/ufo3/kerning.html) it states that glyphs or groups in the kerning pairs are not required to be in the font. But, I do suppose once you're compiling a UFO you'd like to know if there are invalid kerning rules.

I'm not sure what un-called code you're referring to? I'd like to remove any dead code if possible. Thanks!

**Comment by jamesgk** [comment]
> I'm not sure what un-called code you're referring to?

Oh, I guess you were describing the feature class name pattern not being used for UFO groups, never mind.

**Comment by justvanrossum** [comment]
I'm not I follow. If a name used in a kern pair exists as a group name and not as a glyph name then it is a group name. If a name exists as a group name AND as a glyph name, then theres an ambiguitiy and one could say the UFO is broken. If the name exists neither as a group name nor as a glyph name, that's a problem, too, but can perhaps be ignored (with a warning).
So, in general, it's trivial to figure out what are the groups needed for kerning, and it feels clumsy I'd have to subclass KernFeatureWriter just to support legal UFO.

**Comment by graphicore** [comment]
> If a name exists as a group name AND as a glyph name, then theres an ambiguitiy and one could say the UFO is broken.

I think the UFO spec doesn't mention this. But it uses another heuristic, for UFO 2:

http://unifiedfontobject.org/versions/ufo2/kerning.html

>  If a member of a pair has a name that is defined as a group name in groups.plist, assume that the member is a group. Applications that allow group editing should take care to prevent conflicts in groups used for kerning.

UFO 3 is quite specific about kerning group names:

http://unifiedfontobject.org/versions/ufo3/groups.html

> Kerning groups must begin with standard prefixes. The prefix for groups intended for use in the first side of a kerning pair is "public.kern1.". The prefix for groups intended for use in the second side of a kerning pair is "public.kern2."

**Comment by justvanrossum** [comment]
The spec wins. Either way, it's trivial to make an implementation that does the right thing for both UFO2 and UFO3 without the need to subclass KernFeatureWriter. Which was my point.

**Comment by adrientetar** [comment]
> I think the UFO spec doesn't mention this.

It does:

> In UFO 1 and UFO 2, the implication was that if a member of a kerning pair had the same name as a group and a glyph, that member was the group.

http://unifiedfontobject.org/versions/ufo3/kerning.html

**Comment by graphicore** [comment]
@adrientetar you have to read the whole thing:

>>  If a name exists as a group name AND as a glyph name, then theres an ambiguitiy and one could say the UFO is broken.
> I think the UFO spec doesn't mention this. But it uses another heuristic, for UFO 2:

**Comment by adrientetar** [comment]
Right &ndash; but from that sentence about forward-conversion, and althrough it's not explicitly stated, one may infer that the following covers glyph names too:

> Only kerning groups are allowed to use the kerning group prefixes in their names.

http://unifiedfontobject.org/versions/ufo3/groups.html

> Either way, it's trivial to make an implementation that does the right thing for both UFO2 and UFO3 without the need to subclass KernFeatureWriter. Which was my point.

True. Was this code removed from ufo2fdk over speed concerns or something?

**Comment by jamesgk** [comment]
> Was this code removed from ufo2fdk over speed concerns or something?

ufo2ft's kern writer was written from scratch to be very simple (originally <100 lines); it just put whatever was in the UFO into a feature definition with minimal-to-no processing (most of the code was for processing the existing feature syntax). Now of course it's grown a bit as it's become more generalized. I don't have any problem adding this back in.

**Comment by adrientetar** [comment]
I will use ufo2ft to generate fonts in real-time for things like generating bitmaps so unless there's a reason to add this back in I don't have any particular desire for it. I don't think I've seen a UFO (ufo2/ufo3) where kerning groups weren't set up on a pattern. 
I guess the rationale behind this issue is mainly that it forces you to subclass KernFeatureWriter if you don't have default names.

**Comment by justvanrossum** [comment]
The issue is that ufo2ft simply doesn't work for perfectly fine UFO's.

**Comment by graphicore** [comment]
I filed an issue at the ufo-spec repository unified-font-object/ufo-spec#21 about glyph names vs group names in UFO 3. That discussion is rather off-topic in here.
