### ISSUE TITLE
What's the policy re staying uptodate with ufo2fdk?

### ISSUE THREAD

**Issue by behdad** [googlei18n/ufo2ft#23]
Asking, in the context of this for example:
https://github.com/behdad/fonttools/issues/520#issuecomment-182427347

But in general, we need to know what's the future plan, are we completely diverging?  If yes, we should remove code we don't use.  Or for individual files that we have not changed, make sure to compare and update every once in a while...

**Comment by jamesgk** [comment]
A few months ago I thought it would be infeasible to maintain ufo2ft as a branch of ufo2fdk, thinking they would diverge too much. Now I'm re-evaluating as it seems ufo2ft will be unpleasant to maintain either way. I'm not sure how much the mechanics of feaLib diverge from makeotf; maybe the easiest route is to update ufo2fdk to use feaLib, given some argument?

**Comment by adrientetar** [comment]
> maybe the easiest route is to update ufo2fdk to use feaLib, given some argument?

So that's basically dropping ufo2fdk in favor of ufo2ft&hellip; I'd probably let feaLib stabilize for now. 
Either way, if you look at the commit log of ufo2fdk in recent years, there isn't much changes happening.

Here I think https://github.com/typemytype/ufo2fdk/commit/1d5cdc6a98688fbf60b8db37ad9e9c4d44686204 and https://github.com/typemytype/ufo2fdk/commit/8713490e761026c6ec663dcfabc74112c288f2f6 can be commited, pretty much.

**Comment by adrientetar** [comment]
> If yes, we should remove code we don't use.

Didn't James do that already?

**Comment by davelab6** [comment]
@jamesgk what is your current thinking on this?

**Comment by jamesgk** [comment]
I think ufo2ft is entirely separate from ufo2fdk at this point, no reason to try to pull in upstream changes. Along these lines I wanted to rename the makeotfParts module and possibly outlineOTF as well.

**Comment by anthrotype** [comment]
agreed.

**Comment by brawer** [comment]
From this bug, it looks like there’s common agreement. Closing bug.
