### ISSUE TITLE
Set width of glyphs with GDEF class 3 (mark) to zero?

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/ufo2ft#55]
I noticed that in fonts output by Glyphs, any glyph with GDEF class 3 has a width of zero. Should ufo2ft do the same? If so, we have to go back and change widths the compiled OTF/TTFs after the GDEF table has been compiled by feaLib.

**Comment by khaledhosny** [comment]
One related problem (but practically it happens whether the suggestion here is implemented or not) is that we use heuristics to set glyph classes which can be wrong. Case in the point, I was noticing that HarfBuzz is zeroing the width of spacing marks in (self built copy of) Source Sans Pro, it turns out they were given a mark glyph class because they had mark anchors. This can be considered a font bug of course, but I just wanted to point this out here for consideration.

**Comment by behdad** [comment]
Humm.  Good points.  Let me think about it a bit.

@schriftgestalt, what heuristics does Glyphs use for 1. marking a glyph as Mark in GDEF, and 2. zeroing its advance width?

**Comment by moyogo** [comment]
May I ask why are those glyphs with non zero advance width in the source if they are meant to have zero advance width?

**Comment by schriftgestalt** [comment]
> what heuristics does Glyphs use for 1. marking a glyph as Mark in GDEF, and 2. zeroing its advance width?

1) It the glyphs category is 'Mark' and subCategory is 'Nonspacing' or 'Spacing Combining'.
2) It the glyphs subCategory is 'Nonspacing' 

> May I ask why are those glyphs with non zero advance width in the source if they are meant to have zero advance width?

That has to do with how the edit view in Glyphs works. It you open several non spacing marks at once, they are all on top of each other. And you can't select them for editing by clicking them because they don't have a clickable area.

**Comment by khaledhosny** [comment]
How are the category and subcategory defined?

**Comment by schriftgestalt** [comment]
The are mostly derived from the unicode categories. And in some cases manually adjusted.

**Comment by jamesgk** [comment]
Am I right in thinking that the category/subcategory definitions are those at https://github.com/schriftgestalt/GlyphsInfo/blob/master/GlyphData.xml?

**Comment by schriftgestalt** [comment]
Yes

**Comment by davelab6** [comment]
@jamesgk is this still worthwhile?

**Comment by jamesgk** [comment]
Hmm. Arguably this is another Glyphs-specific thing that should go into glyphsLib. Anyways it's worth addressing at some point but not particularly high-priority.

**Comment by anthrotype** [comment]
See https://github.com/googlei18n/glyphsLib/issues/115
