### ISSUE TITLE
Use "ascender" attribute as fallback for similar info

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/ufo2ft#78]
ufo2ft does all sorts of interesting things to calculate ascenders:
https://github.com/googlei18n/ufo2ft/blob/6184b1493bc4afc6969bd2516d02f3f616cb5484/Lib/ufo2ft/fontInfoData.py#L58
https://github.com/googlei18n/ufo2ft/blob/6184b1493bc4afc6969bd2516d02f3f616cb5484/Lib/ufo2ft/fontInfoData.py#L124
https://github.com/googlei18n/ufo2ft/blob/6184b1493bc4afc6969bd2516d02f3f616cb5484/Lib/ufo2ft/fontInfoData.py#L136

I think it should first try to use the generic "ascender" attribute:
http://unifiedfontobject.org/versions/ufo3/fontinfo.plist/#generic-dimension-information

**Comment by moyogo** [comment]
Although we won’t be affected by the changes since we hardcode openTypeHheaAscender, openTypeOS2TypoAscender, openTypeOS2WinAscent, openTypeOS2WinDescent, there are a few issues.

1. info.ascender may not be related to the lineheight and instead be the value of a font family ascender (approximation top of ascender letters across a family) or even the value of the ascender per font. So using this info.ascender as a default for openTypeHheaAscender, openTypeOS2TypoAscender may be incorrect. For example, with unitsPerEm=1000, if ascender=760 and descender=240, with a linegap=0, then there a serious problem with the lineheight being only 1000.

2. If on top of that the openTypeOS2WinAscent is equal to info.ascender, lots of glyphs will be clipped in GDI applications.

We’d recommend either keeping the current fallbacks or using what Georg recommends in https://github.com/googlei18n/glyphsLib/issues/78#issuecomment-256872115.

**Comment by moyogo** [comment]
For reference, here is how the FontLab manual define "ascender", in Metrics and Dimensions > Basic Font Dimensions:
> Ascender | Position of the font’s ascender line. Usually this is the height of the lowercase ‘b’ character

and how it is in the Glyphs manual, section 7.2.2 Metrics:
> Ascender: the height of tall lowercase letters such as b, d, f,
h, k, l or þ.

**Comment by jamesgk** [comment]
OK, so could we just not use the info.ascender attribute anywhere, and use 1.2 * UPM - descender for openTypeHheaAscender, openTypeOS2TypoAscender, and openTypeOS2WinAscent?

We could alternatively set those values in glyphsLib, but then we have to maintain two (somewhat arbitrary) methods for determining ascent from other metrics. As long as this method is reasonably general I'd prefer to have it here.

**Comment by moyogo** [comment]
> OK, so could we just not use the info.ascender attribute anywhere, and use 1.2 * UPM - descender for openTypeHheaAscender, openTypeOS2TypoAscender, and openTypeOS2WinAscent?

OK.
Users should really set up those values themselves since the OT recommended default lineheight only really works with Western glyphsets, but that’s good enough as a fallback.
